### ISSUE TITLE
Add package.json "name" onto a packages page.

### ISSUE THREAD

**Issue by JustBuddy** [kurotu/vpm-catalog#2]
I wasn't able to get a build working for PR, so writing an issue instead.

I'd love to see the package ID referenced on a packages page, so I can quickly identify a package.

That data is provided in a package.json's "name" property.

Here are some mockups:
Listings, either above or below, whatever looks better to you.
![image](https://github.com/kurotu/vpm-catalog/assets/8122264/c1c2f76b-8599-4c7f-aade-ba123dddd5d6)
![image](https://github.com/kurotu/vpm-catalog/assets/8122264/bf31df67-ff49-4ed8-a8b4-749453791c34)

Package page, some sort of reference in the sidebar.
![image](https://github.com/kurotu/vpm-catalog/assets/8122264/d8971987-b055-4486-b504-84b667b7e51b)

**Comment by kurotu** [comment]
Done in b8a2f51709d66e829883ef9dfe22b5188f353b35.
