### ISSUE TITLE
多言語対応について

### ISSUE THREAD

**Issue by Sayamame-beans** [kurotu/vpm-catalog#5]
現在は英語で記述されていますが、他の言語での表示にも対応出来る枠組みがあると良さそうです。(既に可能でしたら申し訳ありません。)

現在翻訳され得る範囲としては殆どトップページやAboutページぐらいのものではありますが、枠組みがあると翻訳を提供しやすく、ユーザーとしても翻訳されていると馴染みやすいかもしれないと思いました。

**Comment by kurotu** [comment]
フレームワーク側に多言語対応の機能自体はあるはずなのですが、あまり調べられていません。(これまで必要性を感じてなかったのもありますが...)

ALCOMからリンクしたいという話は聞いているので、年内のどこかで見ておきたいと思います。

**Comment by kurotu** [comment]
多言語対応可能にして日本語を追加しました。

https://github.com/kurotu/vpm-catalog/tree/5098e31957b9641ecd5700985090716edf74fe85/src/i18n/resources
