### ISSUE TITLE
検索時、依存関係(vpm dependencies/dependencies)の部分にはヒットしない方が良いかもしれない?

### ISSUE THREAD

**Issue by Sayamame-beans** [kurotu/vpm-catalog#6]
例えば、`com.vrchat.avatars`と入力した際、`Package Name. com.vrchat.avatars`がヒットするのは良いと思うのですが、依存関係の部分がヒットしてしまうと、それは求めているものとは異なるものがヒットしやすいかもしれません。
依存関係の部分は検索対象の文字列から除外することは出来ないでしょうか…?
(legacy packagesやpackage name等は問題なく、むしろヒットする方が良いと考えているので、そこはこのままで良いと思っております。)

依存関係がヒットしないようにするデメリットとしては、ヒットすると関連ツールを探す際に役立つかもしれないという点でしょうか。
どちらが良いかは悩ましいものかもしれません…

参考
![image](https://github.com/user-attachments/assets/cb1ef5a2-b15f-4809-9a2a-2c58f6506579)

**Comment by kurotu** [comment]
検索周りはあまり作り込めていなかったのですが、検索に使っているpagefindの機能としては検索対象とする文言の範囲をHTML側で指定できたと思います。見ておきます。

各ページにpackage.jsonの情報が埋め込まれているのが良くないので、画面として見えているものを対象にするのがいいかなと思ってます。

**Comment by kurotu** [comment]
各パッケージのインデックス対象を以下に制限しました。他の細かいところは要望・使い勝手を見て調整できればと思います。
- README本文
- package name
- legacy packages
- license
- author
